### ISSUE TITLE
How do you make your videos?

### ISSUE THREAD

**Issue by expected-ingot** [NoMagicVideos/NoMagicYouTube#2]
I really like your videos. I really like your cube that dances during the video lol. What editing software do you use? And how do you do the cube

**Comment by NoMagicVideos** [comment]
Hi @expected-ingot! I generally use items in the Adobe Creative Suite, so mainly After Effects, with resources from Illustrator and Photoshop, audio in Audition, and put everything together in Premiere. The blob itself is from Adobe Character Animator, so I design the character, rig it up, and then do some real simple movements with it
