### ISSUE TITLE
What's the name of the font?

### ISSUE THREAD

**Issue by subnut** [NoMagicVideos/NoMagicYouTube#3]
The font in the YouTube channel banner, and the font that you use in your videos.

It looks like I've seen it before.... but I just can't seem to recall the exact name for it. :)

**Comment by expected-ingot** [comment]
I think it's Consolas

**Comment by NoMagicVideos** [comment]
Hi @subnut! The font is called Roboto Mono, you can get it on Google Fonts. A friend turned me towards it a while back, and honestly, it was just the first monospaced font to come to mind that I liked. 

https://fonts.google.com/specimen/Roboto+Mono
