### ISSUE TITLE
Direct Contact?

### ISSUE THREAD

**Issue by GrantGryczan** [NoMagicVideos/NoMagicYouTube#4]
Hello! First I'd like to say I'm very happy that I stumbled across your channel because it's exciting to see a growing YouTuber who is very good at teaching and articulating mathematical concepts, and one who is genuinely interested in sharing their knowledge and abilities with the public in an informative but engaging way.

Although I wish this issue could be a private message, I can't find any way to do that, so unless you think it should be absolutely necessary that I make my inquiry public, could you please contact me directly or give me some sort of direct contact? What I want to discuss personally concerns you and you alone, and I value the opportunity to contact you greatly. My most preferred means of contact is Discord, on which my tag is `Grant#2604`, so if you have a Discord account then I'd most prefer you send me a friend request there. Since I always have Discord open when I'm at my PC, that would be the best way to contact me. It's also a lot nicer than email since it allows for continuous and direct conversation, which is what I'm looking for (whenever you have the time). But if that method isn't convenient for you, my email is grantgryczan@gmail.com.

Worst case, if you are absolutely unwilling to share a direct contact with me, then let me know. But I'd really like to avoid that if possible. The matter I want to discuss regards education and your channel. It's important to me, and it may be to you too, but it's not any sort of business agreement or offer for either of our personal gains.

Looking forward to your response! :)

**Comment by NoMagicVideos** [comment]
Hi Grant, 
Thanks for the support! I'm in the middle of setting up some infrastructure on my end, including ways to contact. For the time being, I've added a temporary contact email you can reach me at in the repository's main README. It is nomagic9777 **at** protonmail **dot** com. I can't guarantee I'll always respond in a timely manner at this point, but feel free to shoot me an email there, at least until I get setup over here :)
